version: "3.8"

networks:
  default:
    name: typingrealm

services:
  typingrealm-web-ui:
    image: ${DOCKER_REGISTRY-}typingrealm-web-ui
    container_name: typingrealm-web-ui
    build:
      context: .
      dockerfile: Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-caddy:
    image: caddy
    container_name: typingrealm-caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./infrastructure-data/prod/caddy_data:/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
