version: "3.8"

networks:
  typingrealm-typing-net:
  default:
    name: typingrealm

services:
  typingrealm-typing-1:
    image: ${DOCKER_REGISTRY-}typingrealm-typing
    container_name: typingrealm-typing-1
    networks:
      - default
      - typingrealm-typing-net
    build:
      context: .
      dockerfile: TypingRealm.Typing.Api/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.production.typing

  typingrealm-typing-2:
    image: ${DOCKER_REGISTRY-}typingrealm-typing
    container_name: typingrealm-typing-2
    networks:
      - default
      - typingrealm-typing-net
    build:
      context: .
      dockerfile: TypingRealm.Typing.Api/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.production.typing

  typingrealm-typing-postgres:
    image: postgres
    container_name: typingrealm-typing-postgres
    networks:
      - typingrealm-typing-net
    ports:
      - 10132:5432
    volumes:
      - ./infrastructure-data/prod/typing/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.production.typing
